name: i_read_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  font_awesome_flutter: ^10.7.0
  flutter_plugin_android_lifecycle: ^2.0.0
  record: ^6.0.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/i_read_pic.png
    - assets/models/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/i_read_pic.png"

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  petitparser: ^7.0.0
  xml: ^6.6.0
